#include "wasm4.h"

//// JOYSTICK AND STUFF ///////////////////////////////////////////////////////////

enum {DIR_U,DIR_L,DIR_D,DIR_R,DIR_C};

uint8_t joystick = DIR_C;

void reset_joystick() { joystick = DIR_C; } /// \o/

/// todo: może jeśli wciśnione są jednocześnie up i down [right i left] to zeruj oba?
void update_joystick() {
    uint8_t gamepad = *GAMEPAD1;
    if (gamepad & BUTTON_UP) joystick = DIR_U;
    if (gamepad & BUTTON_LEFT) joystick = DIR_L;
    if (gamepad & BUTTON_DOWN) joystick = DIR_D;
    if (gamepad & BUTTON_RIGHT) joystick = DIR_R;
}

//// SPRITES AND STUFF ////////////////////////////////////////////////////////////

enum { RS_FLOOR,
       RS_ACTOR_LR, RS_ACTOR_LR2, RS_ACTOR_LR3,
       RS_ACTOR_D, RS_ACTOR_D23, RS_ACTOR_U, RS_ACTOR_U23,
       RS_WALL,RS_WALL_O,RS_DIRT,RS_DIRT2,
       RS_WALL_H1,RS_WALL_H2,RS_WALL_H3,
       RS_PIPE_H,RS_PIPE_H2,RS_PIPE_HE,RS_PIPE_HS,RS_PIPE_T,
       RS_BARELL,
       RS_LEVER_L,RS_LEVER_R,
       RS_BOMB,RS_EXPLOSION12,RS_DETONATOR_0,RS_DETONATOR_1,
       RS_PARTICLE_UDLR,RS_GUN_UDLR,
       RS_EVIL_EYE_C,RS_EVIL_EYE_C2,RS_EVIL_EYE_RL,RS_EVIL_EYE_RL2,
       RS_MIRROR,
       RS_ROBOT_UDLR,RS_JOYSTICK,
       RS_DOOR,
       RS_OXYGEN,
       RS_CRYSTAL,
       RS_ELECTRIC,
       RS_FIRE, RS_SMOKE,
       //RS_TENTACLES1,RS_TENTACLES2,
       RS_CORKSCREW,
       RAW_SPRITES_COUNT };

const uint8_t raw_sprites[RAW_SPRITES_COUNT][16] = {
    { /// RS_FLOOR
      0b00000000,0b00000000,
      0b00010000,0b00000000,
      0b00000000,0b00000100,
      0b00000000,0b00000000,
      0b00000000,0b00000000,
      0b00000000,0b00000000,
      0b00000100,0b00000000,
      0b00000000,0b00000000
    },
    { /// RS_ACTOR_LR
      0b00000001,0b01010000,
      0b00001001,0b01110000,
      0b00001001,0b01110000,
      0b00001001,0b10010000,
      0b00000001,0b10010000,
      0b00000001,0b10010000,
      0b00000001,0b01000000,
      0b00000001,0b01000000
    },
    { /// RS_ACTOR_LR2
      0b00000001,0b01010000,
      0b00001001,0b01110000,
      0b00001001,0b01110000,
      0b00001001,0b10010000,
      0b00000001,0b10010000,
      0b00000001,0b01100000,
      0b00000101,0b01010000,
      0b00000000,0b00010000
    },
    { /// RS_ACTOR_LR3
      0b00000001,0b01010000,
      0b00001001,0b01110000,
      0b00001001,0b01110000,
      0b00001001,0b10010000,
      0b00000001,0b10010000,
      0b00000001,0b10010000,
      0b00000001,0b01010000,
      0b00000001,0b00000000
    },
    { /// RS_ACTOR_D
      0b00000101,0b01010000,
      0b00000111,0b11010000,
      0b00010111,0b11010100,
      0b00010101,0b01010100,
      0b00100110,0b10011000,
      0b00100101,0b01011000,
      0b00000100,0b00010000,
      0b00000100,0b00010000
    },
    { /// RS_ACTOR_D23
      0b00000101,0b01010000,
      0b00000111,0b11010000,
      0b00010111,0b11010100,
      0b00100101,0b01010100,
      0b00100110,0b10011000,
      0b00000101,0b01011000,
      0b00000100,0b00010000,
      0b00000100,0b00000000
    },
    { /// RS_ACTOR_U
      0b00000101,0b01010000,
      0b00000110,0b10010000,
      0b00010110,0b10010100,
      0b00010110,0b10010100,
      0b00010101,0b01010100,
      0b00010101,0b01010100,
      0b00000100,0b00010000,
      0b00000100,0b00010000
    },
    { /// RS_ACTOR_U23
      0b00000101,0b01010000,
      0b00000110,0b10010000,
      0b00010110,0b10010100,
      0b00010110,0b10010100,
      0b00010101,0b01010100,
      0b00000101,0b01010100,
      0b00000100,0b00010000,
      0b00000100,0b00000000
    },
    { /// RS_WALL
      0b10101010,0b10101001,
      0b10101010,0b10100101,
      0b10100101,0b01100101,
      0b10100111,0b11100101,
      0b10100111,0b11100101,
      0b10101010,0b10100101,
      0b10010101,0b01010101,
      0b01010101,0b01010101
    },
    { /// RS_WALL_O
      0b11111111,0b11111110,
      0b11101010,0b10101001,
      0b11101010,0b10101001,
      0b11101011,0b11101001,
      0b11101001,0b01101001,
      0b11101010,0b10101001,
      0b11101010,0b10101001,
      0b10010101,0b01010101
    },
    { /// RS_DIRT
      0b00000000,0b00000101,
      0b00000100,0b00000101,
      0b00000100,0b00000000,
      0b00000000,0b00000100,
      0b00000001,0b01010100,
      0b00010000,0b01100100,
      0b00000000,0b01000000,
      0b00000000,0b00000000
    },
    { /// RS_DIRT2
      0b00000000,0b00000000,
      0b00000001,0b01000000,
      0b00000110,0b01000000,
      0b00010101,0b01000001,
      0b00010101,0b00000000,
      0b00000000,0b00000101,
      0b00000000,0b00000101,
      0b00000000,0b00000000
    },
    { /// RS_WALL_H1
      0b00000000,0b00000000,
      0b11111111,0b11111111,
      0b11111111,0b11111111,
      0b10101010,0b10101010,
      0b10101010,0b10101010,
      0b01010101,0b01010101,
      0b01010101,0b01010101,
      0b00000000,0b00000000
    },
    { /// RS_WALL_H2
      0b00000000,0b00000000,
      0b11111111,0b11111111,
      0b11111111,0b11111111,
      0b10101011,0b11101010,
      0b10101001,0b01101010,
      0b01010101,0b01010101,
      0b01010101,0b01010101,
      0b00000000,0b00000000
    },
    { /// RS_WALL_H3
      0b00000000,0b00000000,
      0b11111111,0b11111111,
      0b11111010,0b10101111,
      0b10101001,0b01101010,
      0b10101011,0b11101010,
      0b01011010,0b10100101,
      0b01010101,0b01010101,
      0b00000000,0b00000000
    },
    { /// RS_PIPE_H
      0b00000000,0b00000000,
      0b00000000,0b00000000,
      0b10101010,0b10101010,
      0b11111111,0b11111111,
      0b01010101,0b01010101,
      0b10101010,0b10101010,
      0b00000000,0b00000000,
      0b00000000,0b00000000
    },
    { /// RS_PIPE_H2
      0b00000000,0b00000000,
      0b00000010,0b10100000,
      0b10101010,0b11101010,
      0b11111111,0b11111111,
      0b01010101,0b01010101,
      0b10101010,0b01101010,
      0b00000010,0b10100000,
      0b00000000,0b00000000
    },
    { /// RS_PIPE_HE
      0b00000000,0b00000000,
      0b00000000,0b00000010,
      0b10101010,0b10101011,
      0b11111111,0b11111111,
      0b01010101,0b01010101,
      0b10101010,0b10101001,
      0b00000000,0b00000010,
      0b00000000,0b00000000
    },
    { /// RS_PIPE_HS
      0b00000000,0b00000000,
      0b10100000,0b00000000,
      0b11110110,0b10101010,
      0b11110111,0b11111111,
      0b10100101,0b01010101,
      0b01010110,0b10101010,
      0b10100000,0b00000000,
      0b00000000,0b00000000
    },
    { /// RS_PIPE_T
      0b00000000,0b00000000,
      0b00000000,0b00000010,
      0b00000000,0b10101011,
      0b00000010,0b11111111,
      0b00001011,0b11101010,
      0b00001011,0b10100101,
      0b00001011,0b10010010,
      0b00101111,0b10011000
    },
    { /// RS_BARELL
      0b00000000,0b00000000,
      0b01010101,0b01010101,
      0b00011011,0b10100100,
      0b00011011,0b10100100,
      0b01010110,0b01010101,
      0b00011011,0b10100100,
      0b00011011,0b10100100,
      0b01010101,0b01010101
    },
    { /// RS_LEVER_L
      0b00000000,0b00000000,
      0b11100000,0b00000000,
      0b10010000,0b00000000,
      0b00100100,0b00000000,
      0b00001001,0b00000000,
      0b00000010,0b01000000,
      0b00010101,0b01010100,
      0b01101110,0b10100101
    },
    { /// RS_LEVER_R
      0b00000000,0b00000000,
      0b00000000,0b00001110,
      0b00000000,0b00001001,
      0b00000000,0b00100100,
      0b00000000,0b10010000,
      0b00000010,0b01000000,
      0b00010101,0b01010100,
      0b01101110,0b10100101
    },
    { /// RS_BOMB
      0b00010000,0b01000100,
      0b00011010,0b01101000,
      0b10010101,0b01011001,
      0b10010111,0b11011001,
      0b01010111,0b11010101,
      0b10010101,0b01011001,
      0b10010110,0b01011001,
      0b00011010,0b01101000
    },
    { /// RS_EXPLOSION12
      0b00100010,0b10001010,
      0b00001011,0b10101100,
      0b10101111,0b11111010,
      0b00111111,0b11111110,
      0b10101111,0b11111110,
      0b10111111,0b11111011,
      0b00101011,0b10111100,
      0b00001000,0b10000010
    },
    { /// RS_DETONATOR_0
      0b01010101,0b01010101,
      0b00000010,0b01000000,
      0b00000010,0b01000000,
      0b00000010,0b01000000,
      0b00000101,0b01010000,
      0b00011110,0b10010100,
      0b00011110,0b10010100,
      0b00011110,0b10010100
    },
    { /// RS_DETONATOR_1
      0b00000000,0b00000000,
      0b00000000,0b00000000,
      0b01010101,0b01010101,
      0b00000010,0b01000000,
      0b00000101,0b01010000,
      0b00011110,0b10010100,
      0b00011110,0b10010100,
      0b00011110,0b10010100
    },
    { /// RS_PARTICLE_UDLR
      0b00000000,0b00000000,
      0b00000000,0b00000000,
      0b00000000,0b00000000,
      0b00000100,0b10001111,
      0b00010000,0b10001111,
      0b00000000,0b00000000,
      0b00000000,0b00000000,
      0b00000000,0b00000000
    },
    { /// RS_GUN_UDLR
      0b01000000,0b00000000,
      0b01110000,0b00000000,
      0b01111001,0b00100000,
      0b01101001,0b11000000,
      0b01101001,0b11000000,
      0b01011001,0b00100000,
      0b01010000,0b00000000,
      0b01000000,0b00000000
    },
    { /// RS_EVIL_EYE_C
      0b10101010,0b10101010,
      0b01010101,0b01010101,
      0b01011010,0b10100101,
      0b01111100,0b00111101,
      0b01111100,0b00111101,
      0b01011111,0b11110101,
      0b01010101,0b01010101,
      0b10101010,0b10101010
    },
    { /// RS_EVIL_EYE_C2
      0b10101010,0b10101010,
      0b01010101,0b01010101,
      0b01011010,0b10100101,
      0b01101010,0b10101001,
      0b01111100,0b00111101,
      0b01011111,0b11110101,
      0b01010101,0b01010101,
      0b10101010,0b10101010
    },
    { /// RS_EVIL_EYE_RL
      0b10101010,0b10101010,
      0b01010101,0b01010101,
      0b01011010,0b10100101,
      0b01111111,0b00001101,
      0b01111111,0b00001101,
      0b01011111,0b11110101,
      0b01010101,0b01010101,
      0b10101010,0b10101010
    },
    { /// RS_EVIL_EYE_RL2
      0b10101010,0b10101010,
      0b01010101,0b01010101,
      0b01011010,0b10100101,
      0b01101010,0b10101001,
      0b01111111,0b00001101,
      0b01011111,0b11110101,
      0b01010101,0b01010101,
      0b10101010,0b10101010
    },
    { /// RS_MIRROR
      0b00000101,0b01010000,
      0b00001010,0b11100000,
      0b00011011,0b10100100,
      0b10011110,0b10100110,
      0b10001010,0b10110010,
      0b10001010,0b11100010,
      0b10000001,0b01000010,
      0b10010000,0b00000110
    },
    { /// RS_ROBOT_UDLR
      0b10100100,0b10100100,
      0b00010000,0b00010010,
      0b01101010,0b10100001,
      0b01101111,0b01100101,
      0b01100101,0b01100101,
      0b01101010,0b10100001,
      0b00010000,0b00010010,
      0b10100100,0b10100100
    },
    { /// RS_JOYSTICK
      0b00001110,0b10010000,
      0b00001110,0b10010000,
      0b00000001,0b01000000,
      0b00000010,0b01000000,
      0b00000010,0b01000000,
      0b00000010,0b01000000,
      0b00111010,0b10100100,
      0b11111010,0b10100101
    },
    { /// RS_DOOR
      0b00101010,0b10101000,
      0b10010101,0b00100101,
      0b10010101,0b00100101,
      0b10010100,0b10010101,
      0b10010010,0b01010101,
      0b10010010,0b01010101,
      0b10010010,0b01010101,
      0b00010101,0b01010100
    },
    { /// RS_OXYGEN
      0b00000010,0b01010000,
      0b00000000,0b01000000,
      0b00000011,0b10010000,
      0b00001110,0b10010100,
      0b00001110,0b10010100,
      0b00001110,0b10010100,
      0b00001110,0b10010100,
      0b00001110,0b10010100
    },
    { /// RS_CRYSTAL
      0b00000000,0b00000000,
      0b00000011,0b10000000,
      0b00001111,0b10100000,
      0b00111111,0b10101000,
      0b00101010,0b01010100,
      0b00001010,0b01010000,
      0b00000010,0b01000000,
      0b00000000,0b00000000
    },
    { /// RS_ELECTRIC
      0b00000000,0b00000000,
      0b00100000,0b00001000,
      0b00111100,0b10000011,
      0b11000011,0b00111100,
      0b00000000,0b11000000,
      0b00101100,0b00001000,
      0b11110011,0b00001011,
      0b00001000,0b00000000
    },
    { /// RS_FIRE
      0b00001100,0b00000000,
      0b11001100,0b00110000,
      0b11111100,0b11110011,
      0b11111011,0b11111111,
      0b00111110,0b11101100,
      0b11111010,0b10101100,
      0b11101010,0b10101011,
      0b11111111,0b11111111
    },
    { /// RS_SMOKE
      0b00000101,0b00000100,
      0b00010101,0b01010101,
      0b01010101,0b01010101,
      0b00010101,0b01010101,
      0b00010101,0b01010100,
      0b01010101,0b01010101,
      0b01010101,0b01010101,
      0b00010101,0b00010100
    },
    /*
    { /// RS_TENTACLES1
      0b00000000,0b00110000,
      0b11101000,0b00100000,
      0b00001010,0b01100100,
      0b00001010,0b00101001,
      0b00001000,0b00101001,
      0b00101000,0b01101010,
      0b10101001,0b01011010,
      0b10100101,0b01011010
    },
    { /// RS_TENTACLES2
      0b00000011,0b01000011,
      0b00100000,0b00011010,
      0b10011000,0b00001001,
      0b11001000,0b00100101,
      0b00001000,0b01101000,
      0b00101001,0b01101000,
      0b10101001,0b01001010,
      0b10100101,0b01011010
    },
    */
    { /// RS_CORKSCREW
      0b00001111,0b11110000,
      0b00111010,0b10100100,
      0b11100000,0b11101001,
      0b11100011,0b10011001,
      0b11101110,0b01001001,
      0b11101001,0b00001001,
      0b00111010,0b10100100,
      0b00000101,0b01010000
    }
};

enum { S_FLOOR,
       S_DIRT, S_DIRT2,
       S_WALL,S_WALL2,S_WALL_H1,S_WALL_V1,
       S_WALL_H2,S_WALL_V2,S_WALL_H3, S_WALL_V3,
       S_DOOR,
       S_PIPE_H1,S_PIPE_V1,S_PIPE_H2,S_PIPE_V2,
       S_PIPE_HE,S_PIPE_VE,S_PIPE_HS,S_PIPE_VS,
       S_PIPE_BR,S_PIPE_UR,S_PIPE_UL,S_PIPE_BL,
       S_EVIL_EYE_C, S_EVIL_EYE_L, S_EVIL_EYE_R,
       S_EVIL_EYE_C2, S_EVIL_EYE_L2, S_EVIL_EYE_R2,
       S_BARELL,
       S_OXYGEN,
       S_CRYSTAL,
       S_PARTICLE_U,S_PARTICLE_D,S_PARTICLE_L,S_PARTICLE_R,
       S_PARTICLE_U2,S_PARTICLE_D2,S_PARTICLE_L2,S_PARTICLE_R2,
       S_EXPLOSION,S_EXPLOSION2,
       S_GUN_U,S_GUN_D,S_GUN_L,S_GUN_R,
       S_BOMB, S_DETONATOR_0,S_DETONATOR_1,
       S_LEVER_L,S_LEVER_R, S_CORKSCREW,
       S_ROBOT_U,S_ROBOT_D,S_ROBOT_L,S_ROBOT_R,S_JOYSTICK,
       S_ELECTRIC_H1, S_ELECTRIC_H2,S_ELECTRIC_V1, S_ELECTRIC_V2,
       S_FIRE1, S_FIRE2,
       S_SMOKE1,S_SMOKE2,S_SMOKE3,S_SMOKE4,
       S_MIRROR,
       //S_TENTACLES_U,S_TENTACLES_D,S_TENTACLES_L,S_TENTACLES_R,
       //S_TENTACLES_U2,S_TENTACLES_D2,S_TENTACLES_L2,S_TENTACLES_R2,
       //S_WATER1, S_WATER2,S_WATER3,S_WATER4,
       S_ACTOR_U,S_ACTOR_D,S_ACTOR_L,S_ACTOR_R,
       S_ACTOR_U2,S_ACTOR_D2,S_ACTOR_L2,S_ACTOR_R2,
       S_ACTOR_U3,S_ACTOR_D3,S_ACTOR_L3,S_ACTOR_R3,
       SPRITES_COUNT };

typedef struct {
    uint8_t raw_sprite_index;
    uint32_t flags;
} sprite_t;

const sprite_t sprites[SPRITES_COUNT] = {
    {RS_FLOOR,BLIT_2BPP},	/// S_FLOOR
    {RS_DIRT,BLIT_2BPP},	/// S_DIRT
    {RS_DIRT2,BLIT_2BPP}, 	/// S_DIRT2
    {RS_WALL,BLIT_2BPP},	/// S_WALL
    {RS_WALL_O,BLIT_2BPP}, 	/// S_WALL2
    {RS_WALL_H1,BLIT_2BPP}, 	/// S_WALL_H1
    {RS_WALL_H1,BLIT_2BPP|BLIT_ROTATE}, 	/// S_WALL_V1
    {RS_WALL_H2,BLIT_2BPP}, 	/// S_WALL_H2
    {RS_WALL_H2,BLIT_2BPP|BLIT_ROTATE}, 	/// S_WALL_V2
    {RS_WALL_H3,BLIT_2BPP}, 	/// S_WALL_H3
    {RS_WALL_H3,BLIT_2BPP|BLIT_ROTATE}, 	/// S_WALL_V3
    {RS_DOOR,BLIT_2BPP}, 	/// S_DOOR
    {RS_PIPE_H,BLIT_2BPP}, 	/// S_PIPE_H1
    {RS_PIPE_H,BLIT_2BPP|BLIT_ROTATE}, 	/// S_PIPE_V1
    {RS_PIPE_H2,BLIT_2BPP}, 	/// S_PIPE_H2
    {RS_PIPE_H2,BLIT_2BPP|BLIT_ROTATE}, 	/// S_PIPE_V2
    {RS_PIPE_HE,BLIT_2BPP}, 	/// S_PIPE_HE
    {RS_PIPE_HE,BLIT_2BPP|BLIT_ROTATE}, 	/// S_PIPE_VE
    {RS_PIPE_HS,BLIT_2BPP}, 	/// S_PIPE_HS
    {RS_PIPE_HS,BLIT_2BPP|BLIT_ROTATE}, 	/// S_PIPE_VS
    {RS_PIPE_T,BLIT_2BPP}, 	/// S_PIPE_BR
    {RS_PIPE_T,BLIT_2BPP|BLIT_ROTATE}, 	/// S_PIPE_UR
    {RS_PIPE_T,BLIT_2BPP|BLIT_FLIP_X|BLIT_FLIP_Y}, 	/// S_PIPE_UL
    {RS_PIPE_T,BLIT_2BPP|BLIT_FLIP_X}, 	/// S_PIPE_BL

    {RS_EVIL_EYE_C,BLIT_2BPP}, 	/// S_EVIL_EYE_C
    {RS_EVIL_EYE_RL,BLIT_2BPP|BLIT_FLIP_X}, 	/// S_EVIL_EYE_L
    {RS_EVIL_EYE_RL,BLIT_2BPP}, 	/// S_EVIL_EYE_R
    {RS_EVIL_EYE_C2,BLIT_2BPP}, 	/// S_EVIL_EYE_C2
    {RS_EVIL_EYE_RL2,BLIT_2BPP|BLIT_FLIP_X}, 	/// S_EVIL_EYE_L2
    {RS_EVIL_EYE_RL2,BLIT_2BPP}, 	/// S_EVIL_EYE_R2

    {RS_BARELL,BLIT_2BPP},	/// S_BARELL
    {RS_OXYGEN,BLIT_2BPP},	/// S_OXYGEN
    {RS_CRYSTAL,BLIT_2BPP},	/// S_CRYSTAL
    {RS_PARTICLE_UDLR,BLIT_2BPP|BLIT_ROTATE},	/// S_PARTICLE_U
    {RS_PARTICLE_UDLR,BLIT_2BPP|BLIT_ROTATE|BLIT_FLIP_X},	/// S_PARTICLE_D
    {RS_PARTICLE_UDLR,BLIT_2BPP|BLIT_FLIP_X},	/// S_PARTICLE_L
    {RS_PARTICLE_UDLR,BLIT_2BPP},	/// S_PARTICLE_R
    {RS_PARTICLE_UDLR,BLIT_2BPP|BLIT_ROTATE|BLIT_FLIP_Y},	/// S_PARTICLE_U2
    {RS_PARTICLE_UDLR,BLIT_2BPP|BLIT_ROTATE|BLIT_FLIP_Y|BLIT_FLIP_X},	/// S_PARTICLE_D2
    {RS_PARTICLE_UDLR,BLIT_2BPP|BLIT_FLIP_X|BLIT_FLIP_Y},	/// S_PARTICLE_L2
    {RS_PARTICLE_UDLR,BLIT_2BPP|BLIT_FLIP_Y},	/// S_PARTICLE_R2
    {RS_EXPLOSION12,BLIT_2BPP},	/// S_EXPLOSION
    {RS_EXPLOSION12,BLIT_2BPP|BLIT_ROTATE},	/// S_EXPLOSION2
    {RS_GUN_UDLR,BLIT_2BPP|BLIT_ROTATE},	/// S_GUN_U
    {RS_GUN_UDLR,BLIT_2BPP|BLIT_ROTATE|BLIT_FLIP_X},	/// S_GUN_D
    {RS_GUN_UDLR,BLIT_2BPP|BLIT_FLIP_X},	/// S_GUN_L
    {RS_GUN_UDLR,BLIT_2BPP},	/// S_GUN_R
    {RS_BOMB,BLIT_2BPP},	/// S_BOMB
    {RS_DETONATOR_0,BLIT_2BPP},	/// S_DETONATOR_0
    {RS_DETONATOR_1,BLIT_2BPP},	/// S_DETONATOR_1
    {RS_LEVER_L,BLIT_2BPP},	/// S_LEVER_L
    {RS_LEVER_R,BLIT_2BPP},	/// S_LEVER_R
    {RS_CORKSCREW,BLIT_2BPP},	/// S_CORKSCREW
    {RS_ROBOT_UDLR,BLIT_2BPP|BLIT_ROTATE},	/// S_ROBOT_U
    {RS_ROBOT_UDLR,BLIT_2BPP|BLIT_ROTATE|BLIT_FLIP_X},	/// S_ROBOT_D
    {RS_ROBOT_UDLR,BLIT_2BPP|BLIT_FLIP_X},	/// S_ROBOT_L
    {RS_ROBOT_UDLR,BLIT_2BPP},	/// S_ROBOT_R
    {RS_JOYSTICK,BLIT_2BPP}, /// S_JOYSTICK
    {RS_ELECTRIC,BLIT_2BPP}, /// S_ELECTRIC_H1
    {RS_ELECTRIC,BLIT_2BPP|BLIT_FLIP_Y}, /// S_ELECTRIC_H2
    {RS_ELECTRIC,BLIT_2BPP|BLIT_ROTATE}, /// S_ELECTRIC_V1
    {RS_ELECTRIC,BLIT_2BPP|BLIT_ROTATE|BLIT_FLIP_Y}, /// S_ELECTRIC_V2
    {RS_FIRE,BLIT_2BPP}, /// S_FIRE1
    {RS_FIRE,BLIT_2BPP|BLIT_FLIP_X}, /// S_FIRE2
    {RS_SMOKE,BLIT_2BPP}, /// S_SMOKE1
    {RS_SMOKE,BLIT_2BPP|BLIT_FLIP_X}, /// S_SMOKE2
    {RS_SMOKE,BLIT_2BPP|BLIT_ROTATE}, /// S_SMOKE3
    {RS_SMOKE,BLIT_2BPP|BLIT_ROTATE|BLIT_FLIP_X}, /// S_SMOKE4
    {RS_MIRROR,BLIT_2BPP},	/// S_MIRROR
    /*
    {RS_TENTACLES1,BLIT_2BPP|BLIT_ROTATE},	/// S_TENTACLES_U
    {RS_TENTACLES1,BLIT_2BPP|BLIT_ROTATE|BLIT_FLIP_X},	/// S_TENTACLES_D
    {RS_TENTACLES1,BLIT_2BPP|BLIT_FLIP_X},	/// S_TENTACLES_L
    {RS_TENTACLES1,BLIT_2BPP},	/// S_TENTACLES_R
    {RS_TENTACLES2,BLIT_2BPP|BLIT_ROTATE},	/// S_TENTACLES_U2
    {RS_TENTACLES2,BLIT_2BPP|BLIT_ROTATE|BLIT_FLIP_X},	/// S_TENTACLES_D2
    {RS_TENTACLES2,BLIT_2BPP|BLIT_FLIP_X},	/// S_TENTACLES_L2
    {RS_TENTACLES2,BLIT_2BPP},	/// S_TENTACLES_R2
    */
    {RS_ACTOR_U,BLIT_2BPP},	/// S_ACTOR_U
    {RS_ACTOR_D,BLIT_2BPP},	/// S_ACTOR_D
    {RS_ACTOR_LR,BLIT_2BPP|BLIT_FLIP_X},	/// S_ACTOR_L
    {RS_ACTOR_LR,BLIT_2BPP},	/// S_ACTOR_R
    {RS_ACTOR_U23,BLIT_2BPP},	/// S_ACTOR_U2
    {RS_ACTOR_D23,BLIT_2BPP},	/// S_ACTOR_D2
    {RS_ACTOR_LR2,BLIT_2BPP|BLIT_FLIP_X},	/// S_ACTOR_L2
    {RS_ACTOR_LR2,BLIT_2BPP},	/// S_ACTOR_R2
    {RS_ACTOR_U23,BLIT_2BPP|BLIT_FLIP_X},	/// S_ACTOR_U3
    {RS_ACTOR_D23,BLIT_2BPP|BLIT_FLIP_X},	/// S_ACTOR_D3
    {RS_ACTOR_LR3,BLIT_2BPP|BLIT_FLIP_X},	/// S_ACTOR_L3
    {RS_ACTOR_LR3,BLIT_2BPP}	/// S_ACTOR_R3
};


void display_sprite(uint8_t spr, int32_t x, int32_t y) {
    sprite_t s = sprites[spr];
    blit(raw_sprites[s.raw_sprite_index],x,y,8,8,s.flags);
}
// also cf OBJECTS AND STUFF below for binding of things,facings,frames to sprites.


//// MAP AND STUFF ////////////////////////////////////////////////////////////////

#define MAP_W 128 /// these must be powers of 2 for cheap rounding,
#define MAP_H 32  /// cf map_at etc.

const uint8_t the_map[MAP_H][MAP_W] = {
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_DIRT,S_DIRT,S_DIRT,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_PIPE_HS,S_PIPE_HS,S_PIPE_HS,S_PIPE_HS,S_PIPE_HS,S_PIPE_BL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_L,S_PIPE_HS,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_BL,S_DIRT,S_DIRT,S_DIRT2,S_DIRT2,S_DIRT2,S_DIRT,S_DIRT2,S_DIRT,S_DIRT2,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_PIPE_BR,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HS,S_PIPE_HE,S_PIPE_HS,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HS,S_PIPE_H1,S_PIPE_HS,S_CORKSCREW,S_PIPE_H1,S_PIPE_BL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_WALL_H2,S_WALL_H2,S_WALL,S_DIRT,S_DIRT,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_HS,S_WALL,S_PIPE_HS,S_PIPE_HS,S_PIPE_HS,S_PIPE_HS,S_PIPE_HE,S_PIPE_H1,S_PIPE_BL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_L,S_PIPE_HS,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_BL,S_DIRT2,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_PIPE_BR,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HS,S_PIPE_HE,S_PIPE_HS,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HS,S_PIPE_HE,S_PIPE_HS,S_PIPE_HS,S_PIPE_BL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_FLOOR,S_WALL,S_FLOOR,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_BR,S_WALL2,S_WALL_H1,S_WALL2,S_WALL_H1,S_WALL2,S_WALL_H1,S_WALL2,S_WALL_H1,S_WALL2,S_WALL_H1,S_WALL_H1,S_WALL_H2,S_WALL_H1,S_WALL,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_L,S_PIPE_HS,S_WALL,S_WALL,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL2,S_WALL,S_WALL2,S_WALL2,S_WALL2,S_WALL,S_WALL2,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_DIRT,S_DIRT2,S_DIRT,S_DIRT2,S_DIRT2,S_WALL_V3,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_D,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_U,S_FLOOR,S_GUN_U,S_FLOOR,S_GUN_U,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_FLOOR,S_WALL,S_FLOOR,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_DIRT2,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_WALL_V3,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_U,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VE,S_FLOOR,S_WALL2,S_FLOOR,S_PIPE_VE,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_U,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VS,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL,S_WALL,S_DIRT,S_DIRT,S_DIRT,S_WALL,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_L,S_WALL,S_WALL_H2,S_WALL_H3,S_WALL_H2,S_WALL_H3,S_WALL,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VS,S_GUN_U,S_PIPE_VS,S_GUN_U,S_PIPE_VS,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_U,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_U,S_PIPE_VS,S_GUN_U,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_U,S_FLOOR,S_GUN_U,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_FLOOR,S_WALL,S_FLOOR,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_DIRT2,S_DIRT,S_DIRT,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_DIRT,S_DIRT2,S_DIRT2,S_DIRT,S_EVIL_EYE_C,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_BR,S_PIPE_HS,S_PIPE_H1,S_PIPE_HE,S_EVIL_EYE_C,S_EVIL_EYE_C,S_EVIL_EYE_C,S_EVIL_EYE_C,S_EVIL_EYE_C,S_EVIL_EYE_C,S_EVIL_EYE_C,S_PIPE_HS,S_PIPE_H1,S_PIPE_HE,S_WALL,S_PIPE_HS,S_PIPE_H1,S_PIPE_H1,S_PIPE_HE,S_EVIL_EYE_C,S_EVIL_EYE_C,S_EVIL_EYE_C,S_EVIL_EYE_C,S_EVIL_EYE_C,S_PIPE_HS,S_PIPE_HE,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_DIRT,S_DIRT2,S_DIRT,S_WALL,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_L,S_WALL,S_PIPE_BR,S_PIPE_H1,S_PIPE_H1,S_PIPE_H2,S_WALL,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VE,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_DIRT,S_DIRT2,S_PIPE_VS,S_DIRT,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_DIRT,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_DIRT,S_WALL2,S_WALL_H1,S_WALL_H3,S_WALL_H3,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_DIRT,S_DIRT,S_DIRT,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_PIPE_V1,S_PIPE_BR,S_PIPE_H1,S_PIPE_H1,S_PIPE_HE,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_U,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_U,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_BR,S_WALL2,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VS,S_DIRT2,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_FLOOR,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_BR,S_PIPE_H1,S_PIPE_H1,S_PIPE_H1,S_PIPE_H2,S_PIPE_H1,S_CORKSCREW,S_PIPE_H1,S_PIPE_H2,S_PIPE_H1,S_PIPE_H1,S_PIPE_H2,S_PIPE_H1,S_PIPE_H1,S_WALL,S_PIPE_H1,S_PIPE_H1,S_PIPE_H1,S_WALL,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_L,S_WALL,S_PIPE_V1,S_PIPE_V1,S_PIPE_BR,S_PIPE_H1,S_WALL,S_WALL,S_WALL,S_WALL,S_WALL_H1,S_WALL_H2,S_WALL2,S_WALL,S_WALL2,S_WALL_H2,S_WALL,S_WALL_H1,S_WALL2,S_WALL,S_WALL2,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_WALL_V2,S_PIPE_VE,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VS,S_FLOOR,S_PIPE_BR,S_PIPE_HE,S_PIPE_H1,S_PIPE_HE,S_PIPE_HE,S_PIPE_H1,S_PIPE_HE,S_PIPE_HE,S_GUN_R,S_FLOOR,S_PIPE_V1,S_DIRT,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V3,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_WALL,S_DIRT2,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT2,S_DIRT,S_DIRT,S_DIRT2,S_DIRT2,S_DIRT2,S_DIRT,S_DIRT2,S_DIRT,S_DIRT2,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_PIPE_V1,S_PIPE_V1,S_PIPE_V1,S_PIPE_BR,S_PIPE_H1,S_PIPE_H1,S_PIPE_H1,S_PIPE_HE,S_PIPE_HE,S_PIPE_BL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_WALL_V1,S_PIPE_UR,S_PIPE_HE,S_PIPE_H1,S_PIPE_HE,S_PIPE_H1,S_PIPE_HE,S_WALL2,S_FLOOR,S_WALL2,S_PIPE_HE,S_PIPE_H1,S_PIPE_HE,S_PIPE_HE,S_GUN_R,S_GUN_D,S_FLOOR,S_PIPE_VE,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_DIRT,S_FLOOR,S_FLOOR,S_FLOOR,S_EVIL_EYE_C,S_FLOOR,S_EVIL_EYE_C,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V2,S_EVIL_EYE_C,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT,S_DIRT,S_DIRT,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_PIPE_V1,S_PIPE_V1,S_PIPE_V1,S_PIPE_V1,S_PIPE_BR,S_PIPE_BR,S_PIPE_BR,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_BL,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V3,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_WALL_V1,S_DIRT,S_DIRT2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VE,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VS,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_FLOOR,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_PIPE_H1,S_PIPE_H1,S_PIPE_HE,S_DIRT2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_WALL,S_DIRT,S_DIRT2,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_DIRT2,S_DIRT,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_PIPE_V1,S_PIPE_V1,S_PIPE_V1,S_PIPE_V1,S_PIPE_V1,S_PIPE_V1,S_PIPE_V1,S_PIPE_BR,S_PIPE_HE,S_PIPE_HE,S_PIPE_BL,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_WALL_V2,S_DIRT2,S_DIRT,S_DIRT,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VE,S_DIRT,S_FLOOR,S_PIPE_BR,S_PIPE_HE,S_PIPE_HE,S_PIPE_H1,S_PIPE_HE,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_DIRT,S_FLOOR,S_WALL_V2,S_FLOOR,S_WALL_V3,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_PIPE_BR,S_PIPE_H1,S_CORKSCREW,S_PIPE_H2},
{S_WALL_H1,S_WALL_H1,S_WALL_H2,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H2,S_WALL_H2,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL2,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_EVIL_EYE_C,S_EVIL_EYE_C,S_EVIL_EYE_C,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_PIPE_VS,S_PIPE_VS,S_PIPE_VS,S_PIPE_VS,S_PIPE_VS,S_PIPE_VS,S_PIPE_VS,S_EVIL_EYE_C,S_WALL,S_WALL_H2,S_WALL2,S_FLOOR,S_WALL2,S_WALL_H2,S_WALL,S_WALL_H1,S_WALL2,S_FLOOR,S_WALL2,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_WALL_H3,S_WALL_H2,S_WALL_H2,S_WALL_H3,S_WALL_H2,S_WALL_H2,S_WALL_H3,S_WALL_H2,S_WALL_H2,S_WALL_H3,S_WALL_H2,S_WALL_H2,S_WALL_H3,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL2,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL2,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL2,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H2,S_WALL_H2,S_WALL2,S_WALL2,S_WALL2,S_WALL_H2,S_WALL,S_WALL_H2,S_WALL_H2,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_D,S_FLOOR,S_GUN_D,S_FLOOR,S_FLOOR,S_GUN_D,S_GUN_D,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_WALL,S_WALL_H2,S_WALL_H2,S_WALL_H2,S_WALL_H2,S_WALL_H2,S_WALL,S_EVIL_EYE_C,S_WALL,S_WALL_H1,S_WALL_H2,S_WALL_H2,S_WALL_H1,S_WALL,S_DIRT2,S_WALL,S_FLOOR,S_WALL,S_EVIL_EYE_C,S_WALL,S_WALL2,S_WALL2,S_WALL,S_WALL,S_EVIL_EYE_C,S_WALL,S_FLOOR,S_WALL,S_WALL2,S_WALL,S_FLOOR,S_WALL,S_WALL2,S_WALL,S_FLOOR,S_WALL,S_WALL2,S_WALL,S_FLOOR,S_WALL,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_EVIL_EYE_C,S_WALL,S_WALL_H1,S_WALL,S_PIPE_H1,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL2,S_PIPE_H1,S_WALL2,S_WALL_H1,S_WALL_H1,S_WALL,S_PIPE_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL2,S_PIPE_H2,S_PIPE_H2,S_PIPE_H2,S_WALL,S_PIPE_HE,S_EVIL_EYE_C,S_WALL2,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_BR,S_PIPE_HS,S_PIPE_HS,S_WALL,S_PIPE_HS,S_PIPE_HS,S_WALL,S_PIPE_HS,S_PIPE_HS,S_WALL,S_PIPE_HS,S_PIPE_HS,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_EVIL_EYE_C,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_DIRT,S_WALL2,S_FLOOR,S_WALL_H3,S_WALL_H1,S_WALL2,S_FLOOR,S_FLOOR,S_PIPE_V1,S_DIRT2,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H2,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VE,S_FLOOR,S_FLOOR,S_WALL_V1,S_DIRT2,S_DIRT,S_DIRT,S_DIRT2,S_DIRT2,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_GUN_L,S_WALL,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_DIRT,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V2,S_DIRT2,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_EVIL_EYE_C,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VE,S_FLOOR,S_FLOOR,S_WALL,S_DIRT,S_DIRT2,S_DIRT,S_DIRT2,S_DIRT,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_BR,S_PIPE_BL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_PIPE_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_DIRT,S_WALL2,S_FLOOR,S_WALL_H3,S_WALL_H1,S_WALL2,S_FLOOR,S_FLOOR,S_PIPE_V1,S_DIRT2,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H2,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL2,S_PIPE_H1,S_PIPE_H2,S_WALL2,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_PIPE_BR,S_WALL2,S_PIPE_HE,S_FLOOR,S_PIPE_HS,S_WALL2,S_FLOOR,S_FLOOR,S_WALL_V1,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT2,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H2,S_WALL_H3,S_WALL_H2,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_GUN_L,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL,S_DIRT2,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL2,S_WALL2,S_WALL,S_WALL,S_WALL,S_WALL,S_FLOOR,S_WALL,S_WALL,S_WALL_H2,S_WALL_H3,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H3,S_WALL_H2,S_WALL,S_WALL_H2,S_WALL_H1,S_WALL_H3,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H3,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_DIRT,S_DIRT2,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_DIRT2,S_WALL_V1,S_DIRT2,S_WALL_V1,S_FLOOR,S_FLOOR,S_GUN_D,S_PIPE_VE,S_DIRT2,S_FLOOR,S_DIRT,S_PIPE_VE,S_FLOOR,S_FLOOR,S_WALL,S_DIRT,S_PIPE_BR,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_UR,S_WALL2,S_PIPE_BL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_DIRT,S_DIRT,S_DIRT2,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_PIPE_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_L,S_PIPE_HS,S_PIPE_HS,S_PIPE_HS,S_PIPE_HS,S_PIPE_HS,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_PIPE_VS,S_EVIL_EYE_C,S_PIPE_VS,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_DIRT,S_DIRT,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_PIPE_HE,S_PIPE_BL,S_FLOOR,S_WALL2,S_PIPE_H2,S_PIPE_H1,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_PIPE_BR,S_WALL2,S_PIPE_H1,S_PIPE_H2,S_PIPE_H1,S_WALL2,S_GUN_R,S_FLOOR,S_WALL2,S_DIRT,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_BR,S_WALL2,S_PIPE_UL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_DIRT,S_DIRT2,S_DIRT,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_WALL_H2,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_DIRT2,S_DIRT2,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V3,S_DIRT2,S_DIRT2,S_DIRT2,S_FLOOR,S_EVIL_EYE_C,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_D,S_FLOOR,S_FLOOR,S_GUN_D,S_PIPE_VS,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_BR,S_WALL2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_EVIL_EYE_C,S_EVIL_EYE_C,S_EVIL_EYE_C,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_DIRT2,S_DIRT,S_DIRT2,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_DIRT2,S_DIRT,S_DIRT,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_UR,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL2,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_UR,S_PIPE_UL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_DIRT2,S_DIRT2,S_DIRT,S_DIRT,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V3,S_DIRT,S_DIRT,S_DIRT2,S_PIPE_BR,S_PIPE_H1,S_CORKSCREW,S_PIPE_H1,S_WALL,S_PIPE_HE,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_PIPE_VS,S_FLOOR,S_PIPE_VS,S_DIRT,S_DIRT2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H3,S_WALL,S_WALL_H3,S_WALL_H1,S_WALL_H3,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL2,S_WALL_H1,S_WALL_H2,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H2,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H2,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H2,S_WALL_H3,S_WALL_H2,S_WALL,S_WALL_H2,S_WALL,S_WALL_H3,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_PIPE_HS,S_PIPE_H1,S_PIPE_H1,S_PIPE_H1,S_PIPE_HE,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL2,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL_H1},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_EVIL_EYE_C,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_PIPE_H1,S_PIPE_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_PIPE_H1,S_PIPE_H1,S_WALL,S_PIPE_H1,S_PIPE_H1,S_PIPE_H1,S_WALL,S_PIPE_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL2,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL2,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL,S_WALL,S_WALL,S_WALL,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1,S_WALL_H1,S_WALL_H3,S_WALL_H1},
{S_FLOOR,S_FLOOR,S_FLOOR,S_DIRT,S_WALL_V1,S_DIRT2,S_DIRT,S_DIRT,S_DIRT2,S_DIRT2,S_DIRT,S_DIRT2,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT2,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V1,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_DIRT,S_DIRT2,S_DIRT2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_DIRT,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_DIRT,S_DIRT2,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL,S_WALL,S_WALL,S_WALL,S_WALL,S_WALL,S_WALL,S_WALL,S_WALL,S_WALL,S_WALL_H1,S_WALL_H1,S_WALL_H1,S_WALL,S_WALL_H2,S_WALL_H2,S_WALL,S_DIRT,S_DIRT,S_WALL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_WALL2,S_GUN_R,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_L,S_PIPE_HS,S_WALL,S_WALL2,S_WALL,S_WALL2,S_WALL,S_WALL2,S_WALL,S_WALL2,S_EVIL_EYE_C,S_WALL2,S_WALL,S_WALL2,S_EVIL_EYE_C,S_WALL2,S_WALL,S_WALL2,S_WALL,S_WALL2,S_EVIL_EYE_C,S_WALL2,S_WALL,S_DIRT2,S_DIRT,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_BR,S_PIPE_HS,S_CORKSCREW,S_PIPE_H1,S_PIPE_H2,S_PIPE_H1,S_PIPE_H2,S_PIPE_H1,S_PIPE_H2,S_PIPE_HE,S_EVIL_EYE_C,S_PIPE_HS,S_PIPE_H2,S_PIPE_BL},
{S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_VS,S_DIRT2,S_DIRT,S_PIPE_VS,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_D,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_WALL_V2,S_DIRT2,S_DIRT,S_DIRT2,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_D,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_GUN_L,S_PIPE_HS,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_BL,S_DIRT,S_DIRT,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_DIRT2,S_DIRT2,S_DIRT,S_DIRT,S_DIRT,S_PIPE_BR,S_PIPE_H1,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HS,S_PIPE_HE,S_PIPE_HS,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_HS,S_PIPE_H1,S_PIPE_HS,S_PIPE_HS,S_CORKSCREW,S_PIPE_HE,S_FLOOR,S_PIPE_UR,S_PIPE_HE,S_FLOOR,S_FLOOR,S_FLOOR,S_PIPE_UR,S_WALL2,S_PIPE_HE,S_PIPE_HE,S_PIPE_HE,S_PIPE_BL,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR,S_FLOOR}};


//uint8_t read_map_at(uint8_t x,uint8_t y) { return the_map[y&(MAP_H-1)][x&(MAP_W-1)]; }
uint8_t read_map_at(uint8_t x,uint8_t y,uint8_t flips) {
    x = x&(MAP_W-1); y = y&(MAP_H-1);
    if(flips==0) return the_map[y][x];
    y=(MAP_H-1)-y; /// can add more weird flips
    switch(the_map[y][x]) {
        case S_GUN_D: return S_GUN_U;
        case S_GUN_U: return S_GUN_D;    
        case S_PIPE_BL: return S_PIPE_UL;
        case S_PIPE_BR: return S_PIPE_UR;
        case S_PIPE_UL: return S_PIPE_BL;
        case S_PIPE_UR: return S_PIPE_BR;            
    } /// lol
    return the_map[y][x];
}

int8_t S1_difference(uint8_t a,uint8_t b,uint8_t r) {
    int8_t d = a-b;
    if(d <= r/2 && d>= -r/2) return d;
    if(d > 0) return d-r;
    return d+r;
}

int8_t S1_distance(uint8_t a,uint8_t b,uint8_t r) {
    int8_t d = S1_difference(a,b,r);
    if(d < 0) return -d;
    return d;
}


//// OBJECTS AND STUFF ////////////////////////////////////////////////////////////

int8_t dx_for(uint8_t dir) {
    if(dir==DIR_R) return 1;
    if(dir==DIR_L) return -1;
    return 0;
}

int8_t dy_for(uint8_t dir) {
    if(dir==DIR_D) return 1;
    if(dir==DIR_U) return -1;
    return 0;
}

int8_t flip_dir(uint8_t dir) {
    if(dir==DIR_U) return DIR_D;
    if(dir==DIR_D) return DIR_U;
    return dir;
}

enum { KIND_NOTHING,
       KIND_HERO,
       KIND_BARELL, KIND_PARTICLE, KIND_EXPLOSION, KIND_GUN,
       KIND_ROBOT, KIND_JOYSTICK,
       KIND_CORKSCREW,
       KIND_DOOR,KIND_MIRROR,KIND_OXYGEN,KIND_CRYSTAL,
       KIND_ELECTRIC,KIND_SMOKE,KIND_FIRE,
       //KIND_TENTACLES,KIND_WATER,
       KIND_DETONATOR_0, KIND_DETONATOR_1, KIND_BOMB, KIND_LEVER,
       KINDS_COUNT };

typedef struct {
    uint8_t kind;
    uint8_t x,y;
    uint8_t facing,move;
    uint8_t counter,max_counter;
    uint8_t label;
} thing_t;

#define MAX_THINGS 1024 // XD
thing_t things[MAX_THINGS];
uint16_t first_free=0,last_occupied=0;


thing_t fresh_thing() { /// just some default values...
    thing_t t;
    t.kind = KIND_NOTHING;
    t.x = 0;t.y = 0;
    t.facing = DIR_C; t.move = DIR_C;
    t.counter = 0; t.max_counter = 0;
    t.label = 0;
    return t;
}

void add_thing(thing_t the_thing) {
    if(first_free<MAX_THINGS) {
        things[first_free] = the_thing;
        if(first_free>last_occupied) last_occupied=first_free;
        while(first_free<MAX_THINGS &&
              things[first_free].kind!=KIND_NOTHING) first_free++;
    }
}

void remove_thing(uint16_t index) {
    things[index].kind = KIND_NOTHING;
    if(index<first_free) first_free = index;
    while(things[last_occupied].kind==KIND_NOTHING && last_occupied>=0) last_occupied--;
}

uint8_t sprite_for_maptile(uint8_t t, uint8_t subframe) {
    (void)(subframe); /// just to avoid "error: unused parameter" thing...    
    /// TODO: animate eyes and water.
    return t; /// will add some animations here TODO
}

uint8_t sprite_for_thing(thing_t *t, uint8_t subframe) {
    switch(t->kind) {
        case KIND_NOTHING: return S_FLOOR; /// not the best idea; not going to happen tho ;)
        case KIND_BARELL: return S_BARELL;
        case KIND_OXYGEN: return S_OXYGEN;
        case KIND_CRYSTAL: return S_CRYSTAL;
        case KIND_CORKSCREW: return S_CORKSCREW;
        case KIND_BOMB: return S_BOMB;
        case KIND_DETONATOR_0: return S_DETONATOR_0;
        case KIND_DETONATOR_1: return S_DETONATOR_1;
        case KIND_JOYSTICK: return S_JOYSTICK;
        case KIND_DOOR: return S_DOOR;
        case KIND_MIRROR: return S_MIRROR;
        case KIND_LEVER: return (t->facing==DIR_R?S_LEVER_R:S_LEVER_L);
        case KIND_EXPLOSION: return (subframe>=4 ? S_EXPLOSION : S_EXPLOSION2);
        case KIND_FIRE: return (subframe>=4 ? S_FIRE1 : S_FIRE2);
        case KIND_ELECTRIC:
           switch(t->facing) {
               case DIR_U: case DIR_D: return (subframe>=4 ? S_ELECTRIC_V1 : S_ELECTRIC_V2);
               default: return (subframe>=4 ? S_ELECTRIC_H1 : S_ELECTRIC_H2);
           }
        case KIND_SMOKE:
            switch(subframe) {
                case 0: case 1: return S_SMOKE1;
                case 2: case 3: return S_SMOKE1;
                case 4: case 5: return S_SMOKE1;
                default: return S_SMOKE4;
            }
            /*
        case KIND_WATER:
            switch((t->x+t->y+(subframe>=4?1:0))%4) {
                case 0: return S_WATER1;
                case 1: return S_WATER2;
                case 2: return S_WATER3;
                case 3: return S_WATER4;
            }
        case KIND_TENTACLES:
            switch(t->facing) {
                case DIR_U: return (subframe>=4 ? S_TENTACLES_U : S_TENTACLES_U2);
                case DIR_L: return (subframe>=4 ? S_TENTACLES_L : S_TENTACLES_L2);
                case DIR_D: return (subframe>=4 ? S_TENTACLES_D : S_TENTACLES_D2);
                case DIR_R: return (subframe>=4 ? S_TENTACLES_R : S_TENTACLES_R2);
            }
            break; // notreached, just-in-case
            */
        case KIND_PARTICLE:
            switch(t->facing) {
                case DIR_U: return (subframe>=4 ? S_PARTICLE_U : S_PARTICLE_U2);
                case DIR_L: return (subframe>=4 ? S_PARTICLE_L : S_PARTICLE_L2);
                case DIR_D: return (subframe>=4 ? S_PARTICLE_D : S_PARTICLE_D2);
                case DIR_R: return (subframe>=4 ? S_PARTICLE_R : S_PARTICLE_R2);
            }
            break; // notreached, just-in-case
        case KIND_GUN:
            switch(t->facing) {
                case DIR_U: return S_GUN_U;
                case DIR_L: return S_GUN_L;
                case DIR_D: return S_GUN_D;
                case DIR_R: return S_GUN_R;
            }
            break; // notreached, just-in-case
        case KIND_ROBOT:
            switch(t->facing) {
                case DIR_U: return S_ROBOT_U;
                case DIR_L: return S_ROBOT_L;
                case DIR_D: return S_ROBOT_D;
                case DIR_R: return S_ROBOT_R;
            }
            break; // notreached, just-in-case
        case KIND_HERO:
            if(t->move==DIR_C) {
                switch(t->facing) {
                    case DIR_U: return S_ACTOR_U;
                    case DIR_L: return S_ACTOR_L;
                    case DIR_D: return S_ACTOR_D;
                    case DIR_R: return S_ACTOR_R;
                }
            }
            switch(t->facing) {
                case DIR_U: return (t->y&1 ? S_ACTOR_U2 : S_ACTOR_U3);
                case DIR_L: return (t->x&1 ? S_ACTOR_L2 : S_ACTOR_L3);
                case DIR_D: return (t->y&1 ? S_ACTOR_D2 : S_ACTOR_D3);
                case DIR_R: return (t->x&1 ? S_ACTOR_R2 : S_ACTOR_R3);
            }
      default: break;
    }
    return S_FLOOR; // notreached
}


//// MORE EDITOR-GENERATED STUFF... ///////////////////////////////////////////////

void initialize_world() {
    uint8_t x,y;
    thing_t t;
    uint16_t i;
    first_free=0;
    last_occupied=0;
    t.kind = KIND_HERO;
    t.x = 60; t.y = 11;
    t.facing = DIR_D; t.move = DIR_C;
    t.counter = 0; t.max_counter = 0;
    add_thing(t);
    //// object #0
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 5; t.y = 1;
    t.facing = DIR_L;
    t.counter = 2; t.max_counter = 5;
    add_thing(t);

    //// object #1
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 5; t.y = 3;
    t.facing = DIR_L;
    t.counter = 4; t.max_counter = 5;
    add_thing(t);

    //// object #2
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 7; t.y = 3;
    t.facing = DIR_R;
    t.counter = 4; t.max_counter = 5;
    add_thing(t);

    //// object #3
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 21; t.y = 4;
    t.facing = DIR_C;
    add_thing(t);

    //// object #4
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 5; t.y = 5;
    t.facing = DIR_L;
    t.counter = 1; t.max_counter = 5;
    add_thing(t);

    //// object #5
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 24; t.y = 6;
    t.facing = DIR_C;
    add_thing(t);

    //// object #6
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 2; t.y = 8;
    t.facing = DIR_C;
    add_thing(t);

    //// object #7
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 4; t.y = 9;
    t.facing = DIR_C;
    add_thing(t);

    //// object #8
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 0; t.y = 11;
    t.facing = DIR_C;
    add_thing(t);

    //// object #9
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 1; t.y = 11;
    t.facing = DIR_C;
    add_thing(t);

    //// object #10
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 21; t.y = 12;
    t.facing = DIR_C;
    add_thing(t);

    //// object #11
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 25; t.y = 18;
    t.facing = DIR_C;
    add_thing(t);

    //// object #12
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 27; t.y = 18;
    t.facing = DIR_C;
    add_thing(t);

    //// object #13
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 106; t.y = 10;
    t.facing = DIR_C;
    add_thing(t);

    //// object #14
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 107; t.y = 9;
    t.facing = DIR_C;
    add_thing(t);

    //// object #15
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 108; t.y = 11;
    t.facing = DIR_C;
    add_thing(t);

    //// object #16
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 110; t.y = 11;
    t.facing = DIR_C;
    add_thing(t);

    //// object #17
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 112; t.y = 12;
    t.facing = DIR_C;
    add_thing(t);

    //// object #18
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 112; t.y = 11;
    t.facing = DIR_C;
    add_thing(t);

    //// object #19
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 112; t.y = 9;
    t.facing = DIR_C;
    add_thing(t);

    //// object #20
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 111; t.y = 12;
    t.facing = DIR_C;
    add_thing(t);

    //// object #21
    t = fresh_thing();
    t.kind = KIND_DETONATOR_0;
    t.x = 121; t.y = 9;
    t.facing = DIR_C;
    add_thing(t);

    //// object #22
    t = fresh_thing();
    t.kind = KIND_BOMB;
    t.x = 125; t.y = 8;
    t.facing = DIR_C;
    add_thing(t);

    //// object #23
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 21; t.y = 1;
    t.facing = DIR_U;
    t.counter = 2; t.max_counter = 5;
    add_thing(t);

    //// object #24
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 23; t.y = 1;
    t.facing = DIR_U;
    t.counter = 2; t.max_counter = 5;
    add_thing(t);

    //// object #25
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 25; t.y = 1;
    t.facing = DIR_U;
    t.counter = 2; t.max_counter = 5;
    add_thing(t);

    //// object #26
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 27; t.y = 1;
    t.facing = DIR_U;
    t.counter = 2; t.max_counter = 5;
    add_thing(t);

    //// object #27
    t = fresh_thing();
    t.kind = KIND_LEVER;
    t.x = 6; t.y = 7;
    t.facing = DIR_R;
    add_thing(t);

    //// object #28
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 68; t.y = 10;
    t.facing = DIR_C;
    add_thing(t);

    //// object #29
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 68; t.y = 23;
    t.facing = DIR_C;
    add_thing(t);

    //// object #30
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 68; t.y = 25;
    t.facing = DIR_C;
    add_thing(t);

    //// object #31
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 68; t.y = 24;
    t.facing = DIR_C;
    add_thing(t);

    //// object #32
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 51; t.y = 18;
    t.facing = DIR_C;
    add_thing(t);

    //// object #33
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 61; t.y = 7;
    t.facing = DIR_C;
    add_thing(t);

    //// object #34
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 62; t.y = 6;
    t.facing = DIR_C;
    add_thing(t);

    //// object #35
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 62; t.y = 7;
    t.facing = DIR_C;
    add_thing(t);

    //// object #36
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 68; t.y = 11;
    t.facing = DIR_C;
    add_thing(t);

    //// object #37
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 18; t.y = 21;
    t.facing = DIR_C;
    add_thing(t);

    //// object #38
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 58; t.y = 1;
    t.facing = DIR_U;
    t.counter = 2; t.max_counter = 5;
    add_thing(t);

    //// object #39
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 58; t.y = 5;
    t.facing = DIR_D;
    t.counter = 1; t.max_counter = 5;
    add_thing(t);

    //// object #40
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 57; t.y = 2;
    t.facing = DIR_L;
    t.counter = 3; t.max_counter = 5;
    add_thing(t);

    //// object #41
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 57; t.y = 3;
    t.facing = DIR_L;
    t.counter = 4; t.max_counter = 5;
    add_thing(t);

    //// object #42
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 57; t.y = 4;
    t.facing = DIR_L;
    t.counter = 5; t.max_counter = 5;
    add_thing(t);

    //// object #43
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 59; t.y = 2;
    t.facing = DIR_R;
    t.counter = 3; t.max_counter = 5;
    add_thing(t);

    //// object #44
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 59; t.y = 3;
    t.facing = DIR_R;
    t.counter = 4; t.max_counter = 5;
    add_thing(t);

    //// object #45
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 59; t.y = 4;
    t.facing = DIR_R;
    t.counter = 5; t.max_counter = 5;
    add_thing(t);

    //// object #46
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 107; t.y = 29;
    t.facing = DIR_C;
    add_thing(t);

    //// object #47
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 104; t.y = 30;
    t.facing = DIR_C;
    add_thing(t);

    //// object #48
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 105; t.y = 31;
    t.facing = DIR_C;
    add_thing(t);

    //// object #49
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 1; t.y = 23;
    t.facing = DIR_L;
    t.counter = 4; t.max_counter = 5;
    add_thing(t);

    //// object #50
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 3; t.y = 21;
    t.facing = DIR_R;
    t.counter = 2; t.max_counter = 5;
    add_thing(t);

    //// object #51
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 7; t.y = 20;
    t.facing = DIR_C;
    add_thing(t);

    //// object #52
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 3; t.y = 23;
    t.facing = DIR_R;
    t.counter = 4; t.max_counter = 5;
    add_thing(t);

    //// object #53
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 58; t.y = 22;
    t.facing = DIR_R;
    t.counter = 3; t.max_counter = 5;
    add_thing(t);

    //// object #54
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 49; t.y = 14;
    t.facing = DIR_D;
    t.counter = 5; t.max_counter = 5;
    add_thing(t);

    //// object #55
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 51; t.y = 14;
    t.facing = DIR_D;
    t.counter = 5; t.max_counter = 5;
    add_thing(t);

    //// object #56
    t = fresh_thing();
    t.kind = KIND_GUN;
    t.x = 52; t.y = 14;
    t.facing = DIR_D;
    t.counter = 5; t.max_counter = 5;
    add_thing(t);

    //// object #57
    t = fresh_thing();
    t.kind = KIND_BOMB;
    t.x = 107; t.y = 11;
    t.facing = DIR_C;
    add_thing(t);

    //// object #58
    t = fresh_thing();
    t.kind = KIND_BOMB;
    t.x = 111; t.y = 10;
    t.facing = DIR_C;
    add_thing(t);

    //// object #59
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 110; t.y = 10;
    t.facing = DIR_C;
    add_thing(t);

    //// object #61
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 65; t.y = 13;
    t.facing = DIR_C;
    add_thing(t);

    //// object #62
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 59; t.y = 13;
    t.facing = DIR_C;
    add_thing(t);

    //// object #63
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 62; t.y = 26;
    t.facing = DIR_C;
    add_thing(t);

    //// object #64
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 82; t.y = 28;
    t.facing = DIR_C;
    add_thing(t);

    //// object #65
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 95; t.y = 26;
    t.facing = DIR_C;
    add_thing(t);

    //// object #66
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 87; t.y = 13;
    t.facing = DIR_C;
    add_thing(t);

    //// object #67
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 104; t.y = 13;
    t.facing = DIR_C;
    add_thing(t);

    //// object #68
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 104; t.y = 6;
    t.facing = DIR_C;
    add_thing(t);

    //// object #69
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 117; t.y = 13;
    t.facing = DIR_C;
    add_thing(t);

    //// object #70
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 6; t.y = 13;
    t.facing = DIR_C;
    add_thing(t);

    //// object #71
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 26; t.y = 17;
    t.facing = DIR_C;
    add_thing(t);

    //// object #72
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 30; t.y = 17;
    t.facing = DIR_C;
    add_thing(t);

    //// object #73
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 34; t.y = 17;
    t.facing = DIR_C;
    add_thing(t);

    //// object #74
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 38; t.y = 17;
    t.facing = DIR_C;
    add_thing(t);

    //// object #75
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 26; t.y = 21;
    t.facing = DIR_C;
    add_thing(t);

    //// object #76
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 23; t.y = 26;
    t.facing = DIR_C;
    add_thing(t);

    //// object #77
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 47; t.y = 31;
    t.facing = DIR_C;
    add_thing(t);

    //// object #78
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 1; t.y = 28;
    t.facing = DIR_C;
    add_thing(t);

    //// object #79
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 7; t.y = 26;
    t.facing = DIR_C;
    add_thing(t);

    //// object #80
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 70; t.y = 13;
    t.facing = DIR_C;
    add_thing(t);

    //// object #81
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 67; t.y = 29;
    t.facing = DIR_C;
    add_thing(t);

    //// object #82
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 16; t.y = 23;
    t.facing = DIR_C;
    add_thing(t);

    //// object #83
    t = fresh_thing();
    t.kind = KIND_ROBOT;
    t.x = 13; t.y = 1;
    t.facing = DIR_R;
    add_thing(t);

    //// object #84
    t = fresh_thing();
    t.kind = KIND_JOYSTICK;
    t.x = 23; t.y = 4;
    t.facing = DIR_C;
    add_thing(t);

    //// object #85
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 84; t.y = 26;
    t.facing = DIR_C;
    add_thing(t);

    //// object #86
    t = fresh_thing();
    t.kind = KIND_ROBOT;
    t.x = 89; t.y = 22;
    t.facing = DIR_D;
    add_thing(t);

    //// object #87
    t = fresh_thing();
    t.kind = KIND_DOOR;
    t.x = 101; t.y = 25;
    t.facing = DIR_C;
    add_thing(t);

    //// object #88
    t = fresh_thing();
    t.kind = KIND_JOYSTICK;
    t.x = 86; t.y = 23;
    t.facing = DIR_C;
    add_thing(t);

    //// object #89
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 71; t.y = 18;
    t.facing = DIR_U;
    add_thing(t);

    //// object #90
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 71; t.y = 19;
    t.facing = DIR_U;
    add_thing(t);

    //// object #91
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 69; t.y = 19;
    t.facing = DIR_U;
    add_thing(t);

    //// object #92
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 69; t.y = 18;
    t.facing = DIR_U;
    add_thing(t);

    //// object #93
    t = fresh_thing();
    t.kind = KIND_LEVER;
    t.x = 68; t.y = 12;
    t.facing = DIR_L;
    add_thing(t);

    //// object #94
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 85; t.y = 24;
    t.facing = DIR_L;
    add_thing(t);

    //// object #95
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 86; t.y = 24;
    t.facing = DIR_L;
    add_thing(t);

    //// object #96
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 87; t.y = 24;
    t.facing = DIR_L;
    add_thing(t);

    //// object #97
    t = fresh_thing();
    t.kind = KIND_LEVER;
    t.x = 36; t.y = 0;
    t.facing = DIR_L;
    add_thing(t);

    //// object #98
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 18; t.y = 13;
    t.facing = DIR_L;
    add_thing(t);

    //// object #99
    t = fresh_thing();
    t.kind = KIND_OXYGEN;
    t.x = 3; t.y = 9;
    t.facing = DIR_C;
    add_thing(t);

    //// object #100
    t = fresh_thing();
    t.kind = KIND_OXYGEN;
    t.x = 2; t.y = 9;
    t.facing = DIR_C;
    add_thing(t);

    //// object #101
    t = fresh_thing();
    t.kind = KIND_OXYGEN;
    t.x = 106; t.y = 12;
    t.facing = DIR_C;
    add_thing(t);

    //// object #102
    t = fresh_thing();
    t.kind = KIND_OXYGEN;
    t.x = 76; t.y = 23;
    t.facing = DIR_C;
    add_thing(t);

    //// object #103
    t = fresh_thing();
    t.kind = KIND_CRYSTAL;
    t.x = 50; t.y = 3;
    t.facing = DIR_C;
    add_thing(t);

    //// object #104
    t = fresh_thing();
    t.kind = KIND_LEVER;
    t.x = 99; t.y = 25;
    t.facing = DIR_L;
    add_thing(t);

    //// object #105
    t = fresh_thing();
    t.kind = KIND_MIRROR;
    t.x = 91; t.y = 19;
    t.facing = DIR_C;
    add_thing(t);

    /*
    //// object #106
    t = fresh_thing();
    t.kind = KIND_TENTACLES;
    t.x = 80; t.y = 9;
    t.facing = DIR_U;
    add_thing(t);

    //// object #107
    t = fresh_thing();
    t.kind = KIND_TENTACLES;
    t.x = 78; t.y = 9;
    t.facing = DIR_U;
    add_thing(t);

    //// object #108
    t = fresh_thing();
    t.kind = KIND_TENTACLES;
    t.x = 46; t.y = 19;
    t.facing = DIR_L;
    add_thing(t);

    //// object #109
    t = fresh_thing();
    t.kind = KIND_TENTACLES;
    t.x = 46; t.y = 20;
    t.facing = DIR_L;
    add_thing(t);

    //// object #110
    t = fresh_thing();
    t.kind = KIND_TENTACLES;
    t.x = 46; t.y = 21;
    t.facing = DIR_L;
    add_thing(t);

    //// object #111
    t = fresh_thing();
    t.kind = KIND_TENTACLES;
    t.x = 28; t.y = 22;
    t.facing = DIR_D;
    add_thing(t);

    //// object #112
    t = fresh_thing();
    t.kind = KIND_TENTACLES;
    t.x = 28; t.y = 23;
    t.facing = DIR_U;
    add_thing(t);
    */

    //// object #113
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 35; t.y = 27;
    t.facing = DIR_U;
    add_thing(t);

    //// object #114
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 79; t.y = 10;
    t.facing = DIR_L;
    add_thing(t);

    /*
    //// object #115
    t = fresh_thing();
    t.kind = KIND_TENTACLES;
    t.x = 78; t.y = 11;
    t.facing = DIR_D;
    add_thing(t);

    //// object #116
    t = fresh_thing();
    t.kind = KIND_TENTACLES;
    t.x = 80; t.y = 11;
    t.facing = DIR_D;
    add_thing(t);
    */

    //// object #117
    t = fresh_thing();
    t.kind = KIND_OXYGEN;
    t.x = 66; t.y = 8;
    t.facing = DIR_C;
    add_thing(t);

    //// object #118
    t = fresh_thing();
    t.kind = KIND_OXYGEN;
    t.x = 48; t.y = 29;
    t.facing = DIR_C;
    add_thing(t);

    //// object #119
    t = fresh_thing();
    t.kind = KIND_CRYSTAL;
    t.x = 121; t.y = 31;
    t.facing = DIR_C;
    add_thing(t);

    //// object #120
    t = fresh_thing();
    t.kind = KIND_CRYSTAL;
    t.x = 119; t.y = 31;
    t.facing = DIR_C;
    add_thing(t);

    //// object #121
    t = fresh_thing();
    t.kind = KIND_BARELL;
    t.x = 55; t.y = 0;
    t.facing = DIR_C;
    add_thing(t);

    //// object #122
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 42; t.y = 7;
    t.facing = DIR_L;
    add_thing(t);

    //// object #123
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 43; t.y = 7;
    t.facing = DIR_L;
    add_thing(t);

    //// object #124
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 45; t.y = 7;
    t.facing = DIR_L;
    add_thing(t);

    //// object #125
    t = fresh_thing();
    t.kind = KIND_ELECTRIC;
    t.x = 44; t.y = 7;
    t.facing = DIR_L;
    add_thing(t);
}



//// GAME MECHANICS AND STUFF /////////////////////////////////////////////////////
uint8_t game_behind_mirror = 0;

void dreamy_palette();
void behind_the_mirror_palette();

void the_other_side() {
    uint16_t t;
    if(game_behind_mirror==1) {
        game_behind_mirror = 0;
        dreamy_palette();
    } else {
        game_behind_mirror = 1;
        behind_the_mirror_palette();
    }
    /// flip all things
    for(t=0;t<=last_occupied;t++) {
        things[t].y = (MAP_H-1) - things[t].y;
        if(things[t].kind != KIND_HERO) {
            things[t].facing = flip_dir(things[t].facing);
            things[t].move = flip_dir(things[t].move);
        } /// the hero doesn't flip as it's her mirror-passing
    }
}


/// ok this is pretty specific but for now...
void explode_all_bombs_with_label(uint8_t label) {
    uint16_t t;
    for(t=0;t<=last_occupied;t++) {
        if(things[t].kind!=KIND_BOMB) continue;
        if(things[t].label==label) {
            things[t].kind = KIND_EXPLOSION;
            things[t].move = DIR_C; things[t].facing = DIR_C;
            things[t].counter = 2; things[t].max_counter = 0;
            /// TODO: chain reaction...
        }
    }
}

int can_move(thing_t *mover) {
    uint16_t t;
    uint8_t nx,ny;
    thing_t *collider,*something;

    if(mover->kind==KIND_NOTHING || mover->move==DIR_C) return 0;

    nx = (mover->x+dx_for(mover->move)) & (MAP_W-1);
    ny = (mover->y+dy_for(mover->move)) & (MAP_H-1);
    /// collision with map?
    if(read_map_at(nx,ny,game_behind_mirror)!=S_FLOOR) return 0; /// XD
    /// then maybe with other object?
    for(t=0;t<=last_occupied;t++) {
        if(things[t].kind==KIND_NOTHING) continue;
        if(things[t].x==nx && things[t].y==ny) {
            collider = &things[t];
            /// na szybkości TMP
            if(mover->kind==KIND_HERO && collider->kind==KIND_DOOR) {
                remove_thing(t); /// the collider
                return 0;
            }
            if(mover->kind==KIND_HERO && collider->kind==KIND_MIRROR) {
                if(mover->move==DIR_U || mover->move==DIR_D) {
                    the_other_side(); /// :o
                    return 1;
                }
            }
            
            switch(collider->kind) {
                case KIND_NOTHING:
                    mover->x = nx; mover->y = ny;
                    return 1;

                case KIND_GUN:
                    collider->facing = mover->facing;
                    return 0;

                case KIND_DETONATOR_0:
                    collider->kind = KIND_DETONATOR_1;
                    explode_all_bombs_with_label(collider->label); /// XD
                    return 0;

                case KIND_BARELL: /// TODO: other pushables...
                case KIND_BOMB:
                case KIND_MIRROR: /// with the exception of frontal passing it's pushable
                    collider->move = mover->move;
                    if(can_move(collider)) {
                        mover->x = nx; mover->y = ny;
                        return 1;
                    }
                    collider->move=DIR_C;
                    return 0;

                //// TODO :)

                default: return 0;
            }
         } 
     } 
     /// boom just move'em. 
     mover->x = nx; 
     mover->y = ny; 
     return 1; 
 } 


void update_world() {
    uint16_t t;
    thing_t newthing;

    /// cleanup after previous step (animation info and stuff?)
    for(t=0;t<=last_occupied;t++) {
        if(things[t].kind==KIND_NOTHING) continue;
        things[t].move = DIR_C;
    }
    /// and the new stuff (moves, collisions, whatever)
    for(t=0;t<=last_occupied;t++) {
        if(things[t].kind==KIND_NOTHING) continue;
        switch(things[t].kind) {
            case KIND_HERO:
                things[t].move = joystick;
                if(joystick!=DIR_C) {
                    things[t].facing = joystick;
                    reset_joystick(); /// hehe.
                }
                if(!can_move(&things[t])) things[t].move = DIR_C;
                break;
            case KIND_PARTICLE:
                things[t].move = things[t].facing;
                if(!can_move(&things[t])) {
                    things[t].kind = KIND_EXPLOSION; /// TODO: ESKTRAKCJA EKSPLOZJI WIESZ?!
                    things[t].facing = DIR_C; things[t].move = DIR_C;
                    things[t].counter = 2; things[t].max_counter = 0;
                }
                if(--(things[t].counter)<=0) remove_thing(t); // in case they leak? TODO
                break;
            case KIND_EXPLOSION:
                if(--(things[t].counter)<=0) remove_thing(t); // :)
                break;
            case KIND_GUN:
                if(--(things[t].counter)<=0) {
                    things[t].counter=things[t].max_counter;
                    newthing.kind = KIND_PARTICLE;
                    newthing.facing = things[t].facing;
                    newthing.move = things[t].facing;
                    newthing.x = things[t].x;
                    newthing.y = things[t].y;
                    newthing.counter = 200;
                    add_thing(newthing);
                    can_move(&newthing); /// yup.
                }
                /// guns don't move.
                break;
            case KIND_BARELL:
            case KIND_BOMB:
                break; /// skip the can_move thing, it's managed by the mover.
            /// TODO.
            default:
                if(!can_move(&things[t])) things[t].move = DIR_C;
                break;
        }
    }
}


//// DISPLAY AND STUFF ////////////////////////////////////////////////////////////

#define CENTRE 76 // (SCREEN_SIZE - SPRITE_SIZE)/2 = (190-8)/2 m'kay?

#define VIEW_RADIUS_W 11 // enough to fit the screen + offset for animation
#define VIEW_RADIUS_H 11

uint8_t visible_from(uint8_t src_x,uint8_t src_y,uint8_t tgt_x,uint8_t tgt_y) {
    return (S1_distance(src_x,tgt_x,MAP_W)<=VIEW_RADIUS_W &&
            S1_distance(src_y,tgt_y,MAP_H)<=VIEW_RADIUS_H);
}


void display(uint8_t subframe) {
    uint8_t spr;
    uint8_t x_offset,y_offset;
    int32_t x,y;
    int8_t i,j;
    uint16_t t;
    thing_t *a_thing;
    thing_t *actor = &things[0]; // :D

    //// draw the map
    x_offset = CENTRE + (8-subframe)*dx_for(actor->move);
    y_offset = CENTRE + (8-subframe)*dy_for(actor->move);
    for(j=-VIEW_RADIUS_H;j<=VIEW_RADIUS_H;j++)
        for(i=-VIEW_RADIUS_W;i<=VIEW_RADIUS_W;i++) {
            spr = sprite_for_maptile(read_map_at(actor->x+i,actor->y+j,game_behind_mirror), subframe);
            x = x_offset + i*8;
            y = y_offset + j*8;
            display_sprite(spr,x,y);
        }
    /// and animate objects
    for(t=0;t<=last_occupied;t++) {
        if(things[t].kind==KIND_NOTHING) continue;
        a_thing = &things[t];
        if(visible_from(actor->x,actor->y,a_thing->x,a_thing->y)) {
            spr = sprite_for_thing(a_thing, subframe);
            x = x_offset + S1_difference(a_thing->x,actor->x,MAP_W)*8
                - (8-subframe)*dx_for(a_thing->move);
            y = y_offset + S1_difference(a_thing->y,actor->y,MAP_H)*8
                - (8-subframe)*dy_for(a_thing->move);
            display_sprite(spr,x,y);
        }
    }
}

void dreamy_palette() {
    PALETTE[0] = 0x521296;
    PALETTE[1] = 0x8a1fac;
    PALETTE[2] = 0xd4864a;
    PALETTE[3] = 0xebdb5e;
}

void behind_the_mirror_palette() {
    PALETTE[0] = 0x141433;
    PALETTE[1] = 0x141f66;
    PALETTE[2] = 0x244ab3;
    PALETTE[3] = 0x668fcc;
}


/// THE GAME MAIN DRIVER THINGS ///////////////////////////////////////////////////
uint8_t subframe = 0;


void start() {
    thing_t t;
    subframe = 0;
    game_behind_mirror = 0;
    reset_joystick();
    dreamy_palette();    
    *DRAW_COLORS = 0x4320; // :)
    initialize_world();
}

void update () {
    update_joystick();
    if(subframe==0) update_world();    
    display(subframe++);
    if(subframe==7) reset_joystick(); /// ?!
    if(subframe==8) subframe=0;
}
